main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('resume/', views.resume, name='resume'),
    path('projects/', views.projects, name='projects'),
    path('addmatkul/', views.addmatkul, name='addmatkul'),
    path('deletematkul/<str:pk>/',views.deletematkul, name='deletematkul'),
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('addkegiatan/', views.addkegiatan, name='addkegiatan'),
    path('addperson/', views.addperson, name='addperson'),
    path('books/', views.books, name='books'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

story_ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aboutme/', include('main.urls')),
    path('resume/', include('main.urls')),
    path('projects/', include('main.urls')),
    path('addmatkul/', include('main.urls')),
    path('deletematkul/',include('main.urls')),
    path('kegiatan/', include('main.urls')),
    path('addkegiatan/', include('main.urls')),
    path('addperson/', include('main.urls')),
    path('books/', include('main.urls')),
    path('login/', include('main.urls')),
    path('register/', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class MataKuliah(models.Model):
    nama_matkul = models.CharField(max_length=30)
    kode_matkul = models.CharField(max_length=10)
    dosen = models.CharField(max_length=30)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField()
    semester_tahun = models.CharField(max_length=30)
    ruang_kelas = models.CharField(max_length=30)

    def __str__(self):
        return self.nama_matkul

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=30)
    kode_kegiatan = models.CharField(max_length=5)
    deskripsi_kegiatan = models.TextField()

    def __str__(self):
        return self.nama_kegiatan

class Person(models.Model):
    nama = models.CharField(max_length=30)
    id_person = models.CharField(max_length=5)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import MataKuliah
from .models import Kegiatan, Person
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class MatkulForm(ModelForm):
    class Meta:
        model = MataKuliah
        fields = ['nama_matkul','kode_matkul','dosen','jumlah_sks','deskripsi','semester_tahun','ruang_kelas']

class KegiatanForm(ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama_kegiatan', 'kode_kegiatan', 'deskripsi_kegiatan']

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['nama', 'id_person', 'kegiatan']

class UserForm(UserCreationForm):
    fname = forms.CharField()
    lname = forms.CharField()

    class Meta:
        model = User
        fields = ['fname', 'lname', 'username', 'password1', 'password2']

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import MataKuliah, Kegiatan, Person
from main.forms import MatkulForm, KegiatanForm, PersonForm, UserForm
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
import requests
import json


def home(request):
    return render(request, 'main/home.html')

def aboutme(request):
    matkul = MataKuliah.objects.all()
    response = {}
    response['matkul'] = matkul
    return render(request, 'main/aboutme.html',response)

def resume(request):
    return render(request, 'main/resume.html')

def projects(request):
    return render(request, 'main/projects.html')

def addmatkul(request):
    form = MatkulForm()
    if request.method == 'POST' and form.is_valid:
        form = MatkulForm(request.POST)
        form.save()
        return redirect('/')
    context = {'form':form}

    return render(request, 'main/addmatkul.html', context)

def deletematkul(request, pk):
    matkul = MataKuliah.objects.get(kode_matkul=pk)
    if request.method == 'POST':
        matkul.delete()
        return redirect('/aboutme')

    context ={'item':matkul}
    return render(request, 'main/deletematkul.html', context)

def kegiatan(request):
    kegiatans = Kegiatan.objects.all()
    persons = Person.objects.all()
    response = {}
    response['kegiatans'] = kegiatans
    response['persons'] = persons

    return render(request, 'main/kegiatan.html', response)

def addkegiatan(request):
    form = KegiatanForm()
    if request.method == 'POST' and form.is_valid:
        form = KegiatanForm(request.POST)
        form.save()
        return redirect('/kegiatan')
    context = {'form':form}

    return render(request, 'main/addkegiatan.html', context)

def addperson(request):
    #kegiatan_temp = Kegiatan.objects.get(kode_kegiatan = pk)
    form = PersonForm()
    if request.method == 'POST' and form.is_valid:
        form = PersonForm(request.POST)
        form.save()
        return redirect('/kegiatan')
    context = {'form':form}

    return render(request, 'main/addperson.html', context)

def books(request):

    if request.method == 'GET':
        judul = request.GET.get('judul')
        url = 'https://www.googleapis.com/books/v1/volumes?q=intitle:{}'
        response = requests.get(url.format(judul)).json()
        context = {'data': response['items']}

        print(context['data'])

    return render(request, 'main/books.html', context)

def login(request):

    username = ""
    password = ""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return redirect('/')

    return render(request, 'main/login.html')

def register(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')

    return render(request, 'main/register.html', {'form':form})

def logout(request):
    auth_logout(request)
    return redirect('/login')

main/templates/main/aboutme.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
<link href="https://css.gg/css?=|instagram" rel="stylesheet">
<link href='https://css.gg/twitter.css' rel='stylesheet'> 
<script src="{% static 'js/script.js' %}"></script>
{% endblock meta %} {% block content %}


<div class="container">
  <div class="row" style="margin-top: 50px;margin-left: 40px;">
    <h1>About Me</h1>

    <!-- <p class="par" style="margin-top: 50px;">My name is Hadi Halim Kamil.<br>
                                             I am currrently studying for Bachelor degree majoring in Computer Science
                                             at Universitas Indonesia.<br>
                                             </p> -->
    <!-- Accordion Start-->
    <div class="accordion">
      <div class="accordion-item" id="item1">
        <div class="item-header">
          <h3 class="title">Aktivitas saat ini</h3>
          <div class="icon-up">↑</div>
          <div class="icon-down">↓</div>
        </div>
        <p class="text">
          Lorem ipsum dolor amet
        </p>
      </div>

      <div class="accordion-item" id="item2">
        <div class="item-header">
          <h3 class="title">Pengalaman Organisasi dan Kepanitiaan</h3>
          <div class="icon-up">↑</div>
          <div class="icon-down">↓</div>
        </div>
        <p class="text">
          Lorem ipsum dolor amet
        </p>
      </div>

      <div class="accordion-item" id="item3">
        <div class="item-header">
          <h3 class="title">Prestasi</h3>
          <div class="icon-up">↑</div>
          <div class="icon-down">↓</div>
        </div>
        <p class="text">
          Lorem ipsum dolor amet
        </p>
      </div>

      <div class="accordion-item" id="item4">
        <div class="item-header">
          <h3 class="title">Hobi</h3>
          <div class="icon-up">↑</div>
          <div class="icon-down">↓</div>
        </div>
        <p class="text">
          Lorem ipsum dolor amet
        </p>
      </div>
    </div>

    <!-- Accordion End-->
    
    <p class="par" style="margin-top: 20px;">Here are my courses on this term:</p>

    <a href="{% url 'main:addmatkul' %}" style="color:white">Click here to add a course</a>
    
    {% for each in matkul %}
    <div class="row">
      <div class="col">
        <div class="matkul">
          <h3>{{each.nama_matkul}} {{each.kode_matkul}}</h3>
          <p class="par">Dosen       : {{each.dosen}}<br>
                         Jumlah SKS  : {{each.jumlah_sks}}<br>
                         Deskripsi   : {{each.deskripsi}}<br>
                         Tahun Ajaran: {{each.semester_tahun}}<br>
                         Ruang Kelas : {{each.ruang_kelas}}<br>
          </p>
          <a href="{% url 'main:deletematkul' each.kode_matkul %}">
          <button type="button" class="btn btn-danger">Delete</button>
          
        </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  
  <!-- <div class="row mt-5 ms-2">
    <div class="col">
      <a href="https://www.instagram.com/hadihalimm/">
      <i class="gg-instagram" style="color:white"></i>
      </a>
      <a href="https://twitter.com/hadihalimmm">
        <i class="gg-twitter" style="color:white;margin-top:10px"></i>
        </a>
      </div>
    </div> -->
  </div>
</div>

{% endblock content %}

main/templates/main/addkegiatan.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
{% endblock meta %} {% block content %}

<h1 style="margin-top: 50px;margin-left: 40px;">Tambah Kegiatan</h1>

<div class="container" style="margin-top: 50px;margin-left: 40px;">
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit" style="margin-top: 20px;">
    </form>
</div>

{% endblock content %}

main/templates/main/addmatkul.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
{% endblock meta %} {% block content %}


<h1 style="margin-top: 50px;margin-left: 40px;">Tambah Matkul</h1>

<div class="container" style="margin-top: 50px;margin-left: 40px;">
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit" style="margin-top: 20px;">
    </form>
</div>


{% endblock content %}

main/templates/main/addperson.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
{% endblock meta %} {% block content %}

<h1 style="margin-top: 50px;margin-left: 40px;">Tambah Partisipan {{item}}</h1>

<div class="container" style="margin-top: 50px;margin-left: 40px;">
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <input type="submit" value="Submit" style="margin-top: 20px;">
    </form>
</div>

{% endblock content %}

main/templates/main/books.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
<script src="{% static 'js/script.js' %}"></script>
{% endblock meta %} {% block content %}

<div class="container">
    <div class="row" style="margin-top: 50px;margin-left: 40px;">
        <h1>AJAX Test</h1>
        <form action="" method="GET">
            <div class="form-group" style="margin-top: 30px;">
              <label for="inputbuku">Cari Buku</label>
              <input type="text" name="judul" class="form-control-books" id="inputbuku" aria-describedby="emailHelp" placeholder="Input">
            </div>
            <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Submit</button>
          </form>

          {% for book in data %}
          <h4 style="margin-top: 50px;"> {{ book.volumeInfo.title }} </h4>
          <p class="par">
            Penulis: 
            {% for author in book.volumeInfo.authors %}
            {{ author }},
            {% endfor %}
            <br>
            Penerbit: {{ book.volumeInfo.publisher }} <br>
            Tahun Terbit: {{ book.volumeInfo.publishedDate}} <br>
            Deskripsi: {{ book.volumeInfo.description }} <br>
          </p>
          {% endfor %}
    </div>
</div>

{% endblock content %}

main/templates/main/deletematkul.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>

{% endblock meta %} {% block content %}

<div class="container" style="margin-top: 50px;">
    <p class="par" style="color:white">Are you sure you want to delete "{{item}}" ?</p>

<form action="{% url 'main:deletematkul' item.kode_matkul %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, I'm sure" class="btn btn-light">
</form>
</div>


{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
{% endblock meta %} {% block content %}

<div style="margin-top: 20px; position: absolute; right:20px">
  <h5>Hello, {{ request.user }} </h5>
  <a class="btn btn-danger" href="{% url 'main:logout' %}" role="button">Logout</a>
</div>
<!-- Jumbotron start -->
<section class="jumbotron text-center">
  <img src="{% static 'img/myself.JPG' %}" class="foto img-thumbnail" />
  <h1 class="display-4" style="padding-top: 30px">Hadi Halim Kamil</h1>
  <p class="lead">Student at Universitas Indonesia</p>
</section>
<!-- Jumbotron end -->

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
  <path
    fill="#ffffff"
    fill-opacity="1"
    d="M0,160L48,133.3C96,107,192,53,288,42.7C384,32,480,64,576,90.7C672,117,768,139,864,128C960,117,1056,75,1152,85.3C1248,96,1344,160,1392,192L1440,224L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
  ></path>
</svg>
{% endblock content %}

main/templates/main/kegiatan.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
{% endblock meta %} {% block content %}

<div class="container">
    <div class="row" style="margin-top: 50px;margin-left: 40px;">
      <h1 style="margin-bottom: 50px;">Kegiatan</h1>
      <a href="{% url 'main:addkegiatan' %}" style="color:white">
      <h5 style="margin-bottom: 50px">Klik disini untuk menambah kegiatan</h5>  
      </a>
      {% for item in kegiatans %}
      <div class="col-4 kegiatan" style="margin-bottom:20px">
        <div class="card w-75">
          <div class="card-body">
            <h3 class="card-title">{{item.nama_kegiatan}}</h3>
            <p class="card-text">
              <p>{{item.deskripsi_kegiatan}}</p>
              <p>Daftar Peserta :</p>
        {% for orang in persons %}
          {% if orang.kegiatan == item %}
                  <h6>{{orang.nama}} --- {{orang.id_person}}</h6>
                </p>
          {% endif %}
        {% endfor %}
            </p>
            <div class="flex-container">
              <a href="{% url 'main:addperson' %}" class="btn btn-primary">Tambah Peserta</a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      

    </div>
</div>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
<script src="{% static 'js/script.js' %}"></script>
{% endblock meta %} {% block content %}

<div class="card kartu" style="width: 20rem;">
  <div class="card-body black">
    <h2 class="card-title black" style="margin-bottom: 30px;">Login</h2>
    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="inputUsername" class="form-label">Username</label>
        <input type="text" class="form-control" id="uname" name="username">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="pwd" name="password">
      </div>
      <div class="form">
        <button type="submit" class="btn btn-primary login-signup">Login</button>
        <a class="btn btn-warning" href="{% url 'main:register' %}" role="button">Register</a>
      </div>
    </form>
  </div>
</div>


{% endblock content %}

main/templates/main/projects.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
{% endblock meta %} {% block content %}


<div class="container">
  <div class="row mt-5 ms-2">
    <h1>Projects</h1>
  </div>
  <div class="row mt-5 ms-2 text-center">
    <div class="col">
      <img src="{% static 'img/compfest12.jpg' %}" style="width:200px" class="foto img-thumbnail">
      <br><h2 style="margin-top: 30px;">COMPFEST 12</h2>
    </div>
    <div class="col">
      <img src="{% static 'img/kgtk17.jpg' %}" style="width:200px" class="foto img-thumbnail">
      <h2 style="margin-top: 30px;">Kampus Goes To Kampung 17</h2>
    </div>
    <div class="col">
      <img src="{% static 'img/mcf.jpg' %}" style="width:200px" class="foto img-thumbnail">
      <h2 style="margin-top: 30px;">Minang Culture Festival 2020</h2>
    </div>
  </div>
{% endblock content %}

main/templates/main/register.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
<script src="{% static 'js/script.js' %}"></script>
{% endblock meta %} {% block content %}

<div class="card kartu" style="width: 30rem;">
    <div class="card-body">
      <h2 class="card-title black" style="margin-bottom: 30px;">Register</h2>
      <form method="POST" class="black" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="form" style="margin-bottom: 10px;">
                <div class="label">{{ field.label }} </div>
                {{field}}
            <br>
            </div>
        {% endfor %}
      <input type="submit" value="Register" class="btn btn-primary">
    </form>
    </div>
  </div>


{% endblock content %}

main/templates/main/resume.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>storyhadi</title>
{% endblock meta %} {% block content %}


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block meta %} {% endblock meta %}
  </head>

  <body>
    <!-- Navbar start -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#" style="font-weight: 600; padding-left: 30px"
    >hadihalim.</a
  >
  <button
    class="navbar-toggler"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto" style="padding-right: 30px">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:resume' %}">Resume</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:projects' %}">Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:kegiatan' %}">Kegiatan</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:aboutme' %}">About Me</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:login' %}">Login</a>
      </li>
    </ul>
  </div>
</nav>
<!-- Navbar end -->
    {% block content %} {% endblock content %}
  </body>
</html>